questions_list = [
    "O que distingue a ação humana do comportamento animal, de acordo com Mises?",
    "Quais são os pré-requisitos para a ação humana?",
    "Qual a relação entre a praxeologia e a psicologia?",
    "O que é o apriorismo e por que Mises o considera fundamental para a economia?",
    "Explique o princípio do individualismo metodológico.",
    "Qual o papel da razão na ação humana?",
    "Como o polilogismo contesta a lógica e a razão?",
    "Por que a teoria do cálculo econômico é crucial para Mises?",
    "Quais as principais características da economia de mercado?",
    "Quem foi Ludwig von Mises e qual foi sua contribuição para a Escola Austríaca?",
    "Qual a diferença entre bens livres e bens econômicos?",
    "O que define a utilidade marginal?",
    "Explique a lei dos rendimentos decrescentes.",
    "O que distingue o trabalho introvertido do trabalho extrovertido?",
    "Quais são as fontes de prazer no trabalho?",
    "Como a economia de mercado funciona em relação ao tempo?",
    "O que é preferência temporal e qual a sua importância?"
    "Quais as diferentes formas de poupança e como elas se relacionam com o capital?",
    "Explique a natureza do juro originário.",
    "Quais os principais componentes da taxa bruta de juros do mercado?",
    "Como a expansão do crédito afeta a taxa de juros?",
    "Como Mises explica a relação entre a oferta de moeda e o poder aquisitivo?",
    "O que é o teorema da regressão e qual a sua importância?",
    "Quais os diferentes tipos de moeda e quais as suas características?",
    "Como Mises analisa o surgimento da moeda fiduciária?",
    "O que é o padrão-ouro e quais suas vantagens?",
    "Explique o conceito de " "entesouramento" " e por que Mises o considera um mito.",
    "Como a intervenção governamental no sistema monetário gera caos?",
    "O que é o problema do cálculo econômico no socialismo?",
    "Quais as principais falhas do planejamento centralizado?",
    "Qual o papel do governo em uma sociedade livre, segundo Mises?",
    "Explique a falácia da " "economia mista" ".",
    "Quais as consequências do controle de preços?",
    "Como o intervencionismo leva ao socialismo?",
    "Quais os diferentes tipos de intervenção fiscal?",
    "Explique a natureza e os efeitos das medidas restritivas à produção.",
    "Por que a busca por preços " "justos" " é uma ilusão?",
    "Quais as características dos preços monopolísticos?",
    "Qual a diferença entre lucro empresarial e ganho monopolístico?",
    "Por que Mises considera o sindicalismo um sistema ineficaz e prejudicial?",
    "Como a doutrina do " "efeito de Ricardo" " é equivocada?",
    "Qual o papel da especulação em uma economia de mercado?",
    "Qual o significado do conceito de " "capital" " para Mises?",
    "Explique a importância da propriedade privada para o funcionamento do livre mercado.",
    "Por que Mises considera a guerra e o socialismo como sistemas incompatíveis com a liberdade e a prosperidade?",
    "Quais os principais problemas da " "economia de guerra" "?",
    "Como o intervencionismo governamental gera a mentalidade anticapitalista?",
    "Quais os principais argumentos em favor da "
    "estabilização"
    " e por que Mises os considera falaciosos",
    "Qual o papel da educação na difusão do pensamento econômico?",
    "Por que Mises acredita que o estudo da economia é crucial para o futuro da liberdade?",
    "O que é o cálculo econômico e por que é importante segundo a Escola Austríaca?",
    "Qual é a teoria do ciclo econômico da Escola Austríaca?",
    "O que é a teoria subjetiva do valor e como ela se diferencia de outras teorias?"
    "Como a Escola Austríaca vê o papel do governo na economia?"

]